services:
    catalog:
        image: aboro/kt_catalog:latest
        networks:
            - app
    nginx:
        image: aboro/kt_nginx:latest
        networks:
            - app
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: password
            POSTGRES_USER: app
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        networks:
            - app
    elasticsearch:
        image: elasticsearch:8.5.1
        environment:
            - http.host=0.0.0.0
            - xpack.security.enabled=false
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - app
volumes:
    db-data:
    elasticsearch-data:
networks:
    app:
