FROM php:8.1-fpm-alpine

ARG USER_GID=1000
ARG USER_UID=1000

RUN apk update && apk add libpq-dev supervisor \
    && docker-php-ext-install pdo pdo_pgsql

# Xdebug
RUN apk add --no-cache --virtual .php_builddeps autoconf g++ make \
    && pecl install -f xdebug \
    && apk del .php_builddeps \
    && docker-php-ext-enable xdebug

COPY devops/docker/php/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Php configs
RUN rm -rf /usr/local/etc/php/php-fpm.d/*.conf
COPY devops/docker/php/conf.d/      /usr/local/etc/php/conf.d
COPY devops/docker/php/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY devops/docker/php/php-fpm.d/   /usr/local/etc/php-fpm.d/

# Supervisor
COPY devops/docker/php/supervisor/supervisord.conf /etc/supervisord.conf
COPY devops/docker/php/supervisor/conf.d/ /etc/supervisor/conf.d

RUN addgroup -g ${USER_GID} app \
  && adduser -D -s /bin/sh -G app -u ${USER_UID} app

RUN mkdir -p /var/www/html \
    && chown -R app:app /var/www/

## Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

USER app
WORKDIR /var/www/html

COPY --chown=app:app composer.json composer.lock ./

CMD ["/usr/bin/supervisord"]
